package root:component;

world root {
  import wasi:cli/environment@0.3.0;
  import wasi:cli/exit@0.3.0;
  import wasi:cli/types@0.3.0;
  import wasi:cli/stdin@0.3.0;
  import wasi:cli/stdout@0.3.0;
  import wasi:cli/stderr@0.3.0;
  import wasi:cli/terminal-input@0.3.0;
  import wasi:cli/terminal-output@0.3.0;
  import wasi:cli/terminal-stdin@0.3.0;
  import wasi:cli/terminal-stdout@0.3.0;
  import wasi:cli/terminal-stderr@0.3.0;
  import wasi:clocks/types@0.3.0;
  import wasi:clocks/monotonic-clock@0.3.0;
  import wasi:clocks/system-clock@0.3.0;
  import wasi:keyvalue/store@0.2.0-draft;
  import wasi:config/store@0.2.0-rc.1;
  import wasi:http/types@0.3.0;

  export wasi:cli/run@0.3.0;
  export wasi:http/handler@0.3.0;
}
package wasi:cli@0.3.0 {
  interface environment {
    get-arguments: func() -> list<string>;
  }
  interface exit {
    exit: func(status: result);

    exit-with-code: func(status-code: u8);
  }
  interface types {
    enum error-code {
      io,
      illegal-byte-sequence,
      pipe,
    }
  }
  interface stdin {
    use types.{error-code};

    read-via-stream: func() -> tuple<stream<u8>, future<result<_, error-code>>>;
  }
  interface stdout {
    use types.{error-code};

    write-via-stream: func(data: stream<u8>) -> future<result<_, error-code>>;
  }
  interface stderr {
    use types.{error-code};

    write-via-stream: func(data: stream<u8>) -> future<result<_, error-code>>;
  }
  interface terminal-input {
    resource terminal-input;
  }
  interface terminal-output {
    resource terminal-output;
  }
  interface terminal-stdin {
    use terminal-input.{terminal-input};

    get-terminal-stdin: func() -> option<terminal-input>;
  }
  interface terminal-stdout {
    use terminal-output.{terminal-output};

    get-terminal-stdout: func() -> option<terminal-output>;
  }
  interface terminal-stderr {
    use terminal-output.{terminal-output};

    get-terminal-stderr: func() -> option<terminal-output>;
  }
  interface run {
    run: async func() -> result;
  }
}


package wasi:clocks@0.3.0 {
  interface types {
    type duration = u64;
  }
  interface monotonic-clock {
    use types.{duration};

    type mark = u64;

    now: func() -> mark;

    wait-for: async func(how-long: duration);
  }
  interface system-clock {
    record instant {
      seconds: s64,
      nanoseconds: u32,
    }

    now: func() -> instant;
  }
}


package wasi:keyvalue@0.2.0-draft {
  interface store {
    resource bucket {
      get: func(key: string) -> result<option<list<u8>>, error>;
      set: func(key: string, value: list<u8>) -> result<_, error>;
    }

    variant error {
      no-such-store,
      access-denied,
      other(string),
    }

    open: func(identifier: string) -> result<bucket, error>;
  }
}


package wasi:config@0.2.0-rc.1 {
  interface store {
    variant error {
      upstream(string),
      io(string),
    }

    get: func(key: string) -> result<option<string>, error>;
  }
}


package wasi:http@0.3.0 {
  interface types {
    resource request;

    resource fields {
      constructor();
    }

    type trailers = fields;

    record DNS-error-payload {
      rcode: option<string>,
      info-code: option<u16>,
    }

    record TLS-alert-received-payload {
      alert-id: option<u8>,
      alert-message: option<string>,
    }

    record field-size-payload {
      field-name: option<string>,
      field-size: option<u32>,
    }

    variant error-code {
      DNS-timeout,
      DNS-error(DNS-error-payload),
      destination-not-found,
      destination-unavailable,
      destination-IP-prohibited,
      destination-IP-unroutable,
      connection-refused,
      connection-terminated,
      connection-timeout,
      connection-read-timeout,
      connection-write-timeout,
      connection-limit-reached,
      TLS-protocol-error,
      TLS-certificate-error,
      TLS-alert-received(TLS-alert-received-payload),
      HTTP-request-denied,
      HTTP-request-length-required,
      HTTP-request-body-size(option<u64>),
      HTTP-request-method-invalid,
      HTTP-request-URI-invalid,
      HTTP-request-URI-too-long,
      HTTP-request-header-section-size(option<u32>),
      HTTP-request-header-size(option<field-size-payload>),
      HTTP-request-trailer-section-size(option<u32>),
      HTTP-request-trailer-size(field-size-payload),
      HTTP-response-incomplete,
      HTTP-response-header-section-size(option<u32>),
      HTTP-response-header-size(field-size-payload),
      HTTP-response-body-size(option<u64>),
      HTTP-response-trailer-section-size(option<u32>),
      HTTP-response-trailer-size(field-size-payload),
      HTTP-response-transfer-coding(option<string>),
      HTTP-response-content-coding(option<string>),
      HTTP-response-timeout,
      HTTP-upgrade-failed,
      HTTP-protocol-error,
      loop-detected,
      configuration-error,
      internal-error(option<string>),
    }

    resource response {
      new: static func(headers: headers, contents: option<stream<u8>>, trailers: future<result<option<trailers>, error-code>>) -> tuple<response, future<result<_, error-code>>>;
    }

    type headers = fields;
  }
  interface handler {
    use types.{request, response, error-code};

    handle: async func(request: request) -> result<response, error-code>;
  }
}
