spin_manifest_version = 2
[variables]
greet = { default = "hello" }
[[trigger.http]]
route = "/..."
component = "c"
[component.c]
source = "../../apps/app-http-py-p2/app.wasm"
allowed_outbound_hosts = ["https://example.com"]
key_value_stores = ["default"]
variables = { greeting = "{{ greet }} world" }
