spin_manifest_version = 2
[variables]
greet = { default = "hello" }
[[trigger.http]]
route = "/..."
component = "sink5"
[component.sink5]
source = "../../apps/app-sink5/target/wasm32-wasip2/release/app_sink5.wasm"
allowed_outbound_hosts = ["https://example.com"]
key_value_stores = ["default"]
variables = { greeting = "{{ greet }} world" }
